2022-07-12T21:20:50.4548619-03:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2022-07-12T21:20:50.4603648-03:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-07-12T21:20:50.4631744-03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-07-12T21:20:50.4655806-03:00  [INF] Hosting environment: "Development" (c3307c92)
2022-07-12T21:20:50.4678337-03:00  [INF] Content root path: "C:\Users\hreis\source\repos\SensorWeb\SensorWeb" (b5d60022)
2022-07-12T21:21:05.4878597-03:00 0HMJ4CM5C1N5T:0000000F [INF] Busca OK (0cbc04db)
2022-07-12T21:21:25.9492052-03:00 0HMJ4CM5C1N5T:0000000F [INF] Busca OK 1 (8fc4e460)
2022-07-12T21:25:27.0068326-03:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2022-07-12T21:25:27.0120897-03:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-07-12T21:25:27.0137579-03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-07-12T21:25:27.0151100-03:00  [INF] Hosting environment: "Development" (c3307c92)
2022-07-12T21:25:27.0164478-03:00  [INF] Content root path: "C:\Users\hreis\source\repos\SensorWeb\SensorWeb" (b5d60022)
2022-07-12T21:25:40.3796797-03:00 0HMJ4CONPVL60:00000001 [INF] Busca OK (0cbc04db)
2022-07-12T21:25:40.5428539-03:00 0HMJ4CONPVL60:00000001 [INF] Busca OK 1 (8fc4e460)
2022-07-12T22:52:14.0829861-03:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2022-07-12T22:52:14.0939926-03:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-07-12T22:52:14.1176312-03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-07-12T22:52:14.1200256-03:00  [INF] Hosting environment: "Development" (c3307c92)
2022-07-12T22:52:14.1221096-03:00  [INF] Content root path: "C:\Users\hreis\source\repos\SensorWeb\SensorWeb" (b5d60022)
2022-07-12T22:56:16.9504394-03:00 0HMJ4E97HO2HD:00000001 [ERR] An error occurred using the connection to database '"mydb"' on server '"localhost"'. (5fc3407c)
2022-07-12T22:56:17.4299406-03:00 0HMJ4E97HO2HD:00000001 [ERR] An exception occurred while iterating over the results of a query for context type '"Core.SensorContext"'."
""System.InvalidOperationException: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseMySql' call.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
 ---> System.Threading.ThreadAbortException: System error.
   at System.Diagnostics.Debugger.CustomNotification(ICustomDebuggerNotification data)
   at System.Diagnostics.Debugger.NotifyOfCrossThreadDependencySlow()
   at System.Threading.Tasks.Task.InternalWaitCore(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at MySql.Data.EntityFrameworkCore.Storage.Internal.MySQLExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   --- End of inner exception stack trace ---
   at MySql.Data.EntityFrameworkCore.Storage.Internal.MySQLExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()" (f5c7ac34)
System.InvalidOperationException: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseMySql' call.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
 ---> System.Threading.ThreadAbortException: System error.
   at System.Diagnostics.Debugger.CustomNotification(ICustomDebuggerNotification data)
   at System.Diagnostics.Debugger.NotifyOfCrossThreadDependencySlow()
   at System.Threading.Tasks.Task.InternalWaitCore(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at MySql.Data.EntityFrameworkCore.Storage.Internal.MySQLExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   --- End of inner exception stack trace ---
   at MySql.Data.EntityFrameworkCore.Storage.Internal.MySQLExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Linq.SystemCore_EnumerableDebugView`1.get_Items()
2022-07-12T22:56:21.1396326-03:00 0HMJ4E97HO2HD:00000001 [INF] Busca OK (0cbc04db)
